steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/wa-4-aria/genai-simple', '.']

  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/wa-4-aria/genai-simple']

  - name: 'gcr.io/cloud-builders/kubectl'
    args: ['apply', '-f', 'kubernetes/']
    env:
      - 'CLOUDSDK_COMPUTE_REGION=asia-southeast1'
      - 'CLOUDSDK_CONTAINER_CLUSTER=genai-cluster'

images:
  - 'gcr.io/wa-4-aria/genai-simple'

